### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by jschoch** [1602/elm-json-schema#1]
Hello I'm interested in using this for a project but the tests seem to be failing.  It seems that this was recently pulled out of another project of yours.  Is this consumable, are there plans to publish it as an official elm package?

**Comment by 1602** [comment]
Hello @jschoch, I'm very sorry for such a delay in response, notifications of this repo were muted for some unknown reason.

State of this project is an early experiment (basically I was learning elm). I use this code in another project (https://client.automationcloud.net/) to generate some dynamic forms, depending on schema: one API endpoint returns schema, which describes input of another API endpoint.

If this is still a useful idea for you I could make this code working and add some more documentation (not sure this can bypass the publishing procedure as an official repo).

**Comment by amitu** [comment]
I would be interested. Please give some hints.

**Comment by 1602** [comment]
Tests updated and working now. Also added some docs and examples.

Scope of this package could be enormous in theory, so it is a bit scary to publish it, because this is a very minimal attempt to cover json-schema spec just to suit some practical need in one of the pet projects. On the other hand - I believe in success of elm and would be happy to contribute, it is only matter of having free time to do so.

**Comment by 1602** [comment]
good news @amitu @jschoch: plan has changed slightly and I decided to implement draft 6 of json schema in full (with all validations, schema builder and decoder) plus some nice additions for dynamic form rendering and schema building ui (former needs to be transferred from another project and latter is coming soon-ish). Just FYI.

UPD: draft-6 things are already implemented (ready to review), but I plan send request to publish stuff in the end of September when UI components are ready
